// 1. Create 2 users in the same group
// 2. Assign a task to each with freq=daily, rotating=true, expiring today at 11:59 PM
// 3. Run cronojob to see if it assigns them to the other user

@baseUrl = http://localhost:3000


### Create group
POST {{baseUrl}}/group
Content-Type: application/json

{ 
    "name": "Crono group"
}


### Create user 1 
POST {{baseUrl}}/auth/register
Content-Type: application/json

{ 
    "name": "user1", 
    "email": "user1@gmail.com", 
    "username": "user1", 
    "password": "user1" 
}

### Assign the group to user1
POST {{baseUrl}}/usergroup/assign
Content-Type: application/json

{ 
    "idUser": 5, 
    "idGroup": 4
}

### Create one taskDated
POST {{baseUrl}}/taskdated
Content-Type: application/json

{ 
    "idGroup": 4,
    "idTaskTemplate": 3,
    "startDate": "2025-08-19T00:00:00.000Z",
    "endDate": "2025-08-19T23:59:59.000Z",
    "status": "todo",
    "frequency": "daily",
    "rotative": true

}

### Assign this task to user1
POST {{baseUrl}}/usertask/assign
Content-Type: application/json

{ 
    "idUser" : 5,
    "idTaskDated": 14
}


### Create user2
POST {{baseUrl}}/auth/register
Content-Type: application/json

{ 
    "name": "user2", 
    "email": "user2@gmail.com", 
    "username": "user2", 
    "password": "user2" 
}

### Assign the group to user2
POST {{baseUrl}}/usergroup
Content-Type: application/json

{ 
    "idUser": 6, 
    "idGroup": 4
}

### Create one taskDated
POST {{baseUrl}}/taskdated
Content-Type: application/json

{ 
    "idGroup": 4,
    "idTaskTemplate": 4,
    "startDate": "2025-08-19T00:00:00.000Z",
    "endDate": "2025-08-19T23:59:59.000Z",
    "status": "todo",
    "frequency": "daily",
    "rotative": true

}

### Assign this task to user2
POST {{baseUrl}}/usertask/assign
Content-Type: application/json

{ 
    "idUser" : 6,
    "idTaskDated": 11
}


### List tasks user1
GET {{baseUrl}}/user/6/taskdateds