@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOjUsInVzZXJuYW1lIjoiZmxvd2NoZWNrZXIiLCJpYXQiOjE3NTU2MTQzNjMsImV4cCI6MTc1NTYxNTI2M30.EcJq5LrpBqOfaEt0We2gG-3zP2eHuZi-qbE3iCJaduE

### Get users
GET {{baseUrl}}/user 


### Register user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{ 
    "name": "flowchecker", 
    "email": "flowchecker@gmail.com", 
    "username": "flowchecker", 
    "password": "flow123" 
}


### Check token -- password correct
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "flowchecker",
  "password": "flow123"
}


### Access profile
GET {{baseUrl}}/auth/profile
Authorization: Bearer {{token}}