@baseUrl = http://localhost:3000

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOjUsInVzZXJuYW1lIjoiZmxvd2NoZWNrZXIiLCJpYXQiOjE3NTYxNDA2NTEsImV4cCI6MTc1NjE0MTU1MX0.1kW9kaGTMN0scOcLTijgu-mpsKhpvVlwh01OB2h1V58
POST {{baseUrl}}/auth/register
Content-Type: application/json

{ 
    "name": "flowchecker", 
    "email": "flowchecker@gmail.com", 
    "username": "flowchecker", 
    "password": "flow123" 
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "flowchecker",
  "password": "flow123"
}

# Buy List

### Get buy list by task ID
GET {{baseUrl}}/buylist/task/2
Authorization: Bearer {{token}}

### Get buy list by material ID
GET {{baseUrl}}/buylist/material/3
Authorization: Bearer {{token}}

# Group

### Get group users
GET {{baseUrl}}/group/1/users
Authorization: Bearer {{token}}

### Get group tasks
GET {{baseUrl}}/group/1/tasks
Authorization: Bearer {{token}}

### POST to create template
POST {{baseUrl}}/group/1/templates
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id": 1,
    "name": "Plantilla de tarea",
    "description": "Descripción de la plantilla",
    "steps": "Paso 1, Paso 2, Paso 3"
}

### Get group task templates
GET {{baseUrl}}/group/1/templates
Authorization: Bearer {{token}}

### Get group materials
GET {{baseUrl}}/group/1/materials
Authorization: Bearer {{token}}

### Get user tasks by group 1
GET {{baseUrl}}/taskdated/group/1
Authorization: Bearer {{token}}
# Accept: application/json

# Material

### Get material templates
GET {{baseUrl}}/material/2/templates
Authorization: Bearer {{token}}

### Get buy lists
GET {{baseUrl}}/material/3/buylists
Authorization: Bearer {{token}}


# Material task template

### Get materials by template
GET {{baseUrl}}/materialtasktemplate/1/materials
Authorization: Bearer {{token}}

### Get materials by template
GET {{baseUrl}}/materialtasktemplate/2/templates
Authorization: Bearer {{token}}


### Get buy list by tasks ID
POST {{baseUrl}}/user/1/taskDated
Content-Type: application/json

{
    "idUser": 1,
    "idTaskDated": 1
}

//PUT {{baseUrl}}/user/1
Content-Type: application/json

{
    "name": "Usuario Actualizado",
    "email": "actualizado@correo.com"
}

DELETE {{baseUrl}}/user/1


### Create group with PIN (autogenerated)
POST {{baseUrl}}/group/createwithpin
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Matemáticas Avanzadas",
  "link": "https://discord.gg/123",
  "image": "imagen.png"
}


### Get PIN of the group
GET {{baseUrl}}/group/2/pin
Content-Type: application/json
Authorization: Bearer {{token}}


### Join group by PIN
POST {{baseUrl}}/usergroup/join
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "idUser": 3,
  "idGroup": 2,
  "password": "g5go0JK7"
}



### Get tasks by user and date range (today | week | month)
GET {{baseUrl}}/user/1/taskdated/report?filter=today
Authorization: Bearer {{token}}


### Get buy lists by group and date range (today | week | month)
GET {{baseUrl}}/user/1/group/1/buylist/report?filter=today
Authorization: Bearer {{token}}