@baseUrl = http://localhost:3000


///taskDatedRouter.get("/:id/users", taskDatedController.getUsers);

### Get users of taskDated
GET {{baseUrl}}/taskdated/14/users

/// taskDatedRouter.get("/:id/buylists", taskDatedController.getBuyList);

### Get buy list of task by ID taskDated
GET {{baseUrl}}/taskdated/4/buylists


// Specific routes first to avoid conflicts

//taskTemplateRouter.get('/group/:idGroup/:type', taskTemplateController.getTasksByTypeByGroupID);

###  List all taskTemplates by type passed as a variable (task or recipe) by group ID
GET {{baseUrl}}/tasktemplate/group/1/task


//taskTemplateRouter.get('/:idTask/taskdated', taskTemplateController.getTasksByID);

### Get agended tasks (taskDated) of taskTemplate
GET {{baseUrl}}/tasktemplate/3/taskdated


//taskTemplateRouter.get('/:id/materials', taskTemplateController.getMaterials);

### List the required materials by task ID
GET {{baseUrl}}/tasktemplate/3/materials


// Generic route at the end with fixed prefix for type

//taskTemplateRouter.get('/type/:type', taskTemplateController.getByType);

### List all taskTemplates by type passed as a variable (task or recipe)
GET {{baseUrl}}/tasktemplate/type/task